- menu_name: "Web"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Complaints"
  url: "/complaints-procedure/"
  title: "Complaints Procedure"

- name: "Copyright"
  url: "/license/"
  title: "Copyright and Licensing"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "Privacy Policy for kirstinheidler.co.uk"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

